import { MigrationInterface, QueryRunner } from 'typeorm';

export class updateTable1664762748173 implements MigrationInterface {
  name = 'updateTable1664762748173';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "partitioned_audience" ("created_by" character varying, "updated_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "opengpt_campaign_instance_id" character varying(64) NOT NULL, "schedule_id" character varying(32) NOT NULL, "token" character varying(32) NOT NULL, "status" character varying NOT NULL DEFAULT 'todo', CONSTRAINT "PK_cf5a7752df6f872ce9900b1488f" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_e666bc87dfae423d04b5ecc501" ON "partitioned_audience" ("opengpt_campaign_instance_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_5d84b58ba704ed506e644d9e08" ON "partitioned_audience" ("schedule_id") `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX "public"."IDX_5d84b58ba704ed506e644d9e08"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_e666bc87dfae423d04b5ecc501"`,
    );
    await queryRunner.query(`DROP TABLE "partitioned_audience"`);
  }
}
